name: test-mongodb-storage

on: [push]

jobs:
  test-mongodb-storage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4.2
    - name: Optionally install Chromium via APT instead of puppeteer
      run: |
        if [ ! -z "$PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" ]; then
          APT_INSTALL="chromium gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget"
          if [ ! -z "$APT_PROXY" ]; then
            echo "deb $APT_PROXY buster main" > /etc/apt/sources.list
          fi
          apt-get update
          apt-get install -y $APT_INSTALL
        fi
    - name: Set up project
      run: |
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        if [ ! -z "$NPM_PROXY" ]; then
          echo registry=$NPM_PROXY > .npmrc
        fi
        if [ -d /opt/hostedtoolcache/node/ ]; then
          export alias node=`find /opt/hostedtoolcache/node/ -maxdepth 4 -name node`
          export alias npm=`find /opt/hostedtoolcache/node/ -maxdepth 4 -name npm`
        fi
        npm init -y
        npm install "$HERE" @userdashboard/storage-mongodb mocha puppeteer faker
        echo "global.applicationPath = __dirname" > main.js
    - name: Test without data encryption
      run: ./node_modules/.bin/mocha --exit --file main.js --recursive --timeout 90000000 $(find ./node_modules/@userdashboard/*/ -name "*.test.js" | grep -i -v [a-z0-9]/node_modules | sort -k5.1,8.1 -t /)
      working-directory: /tmp/project
      env:
        NODE_ENV: "testing"
        STORAGE: "@userdashboard/storage-mongodb"
        MONGODB_URL: mongodb://localhost:27017
        MONGODB_DATABASE: "dashboard"
        NODE_OPTIONS: --preserve-symlinks
    - name: Test with data encryption
      run: ./node_modules/.bin/mocha --exit --file main.js --recursive --timeout 90000000 $(find ./node_modules/@userdashboard/*/ -name "*.test.js" | grep -i -v [a-z0-9]/node_modules | sort -k5.1,8.1 -t /)
      working-directory: /tmp/project
      env:
        NODE_ENV: "testing"
        STORAGE: "@userdashboard/storage-mongodb"
        MONGODB_URL: mongodb://localhost:27017
        MONGODB_DATABASE: "dashboard"
        ENCRYPTION_SECRET: abc45678901234567890123456789012
        ENCRYPTION_SECRET_IV: abc4123412341234
        NODE_OPTIONS: --preserve-symlinks
