name: test-s3

on: [push]

jobs:
  test-s3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
        ports:
          - 4566:4566
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up as module
      run: |
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-s3
        npm install -g mocha
        rm node_modules/@userdashboard/dashboard/*.js
        rm -rf node_modules/@userdashboard/dashboard/src
        cp $HERE/*.js node_modules/@userdashboard/dashboard
        cp -R $HERE/src/ node_modules/@userdashboard/dashboard/src/
        echo "global.applicationPath = __dirname" > main.js
        aws --endpoint-url=http://localhost:4566 s3 mb s3://testing
      env:
        AWS_SECRET_ACCESS_KEY: "using-mock-aws-s3"
        AWS_ACCESS_KEY_ID: "using-mock-aws-s3"
    - name: Test unencrypted S3-compatible storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-s3"
        S3_ENDPOINT: "http://localhost:4566"
        S3_BUCKET_NAME: "testing"
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test encrypted S3-compatible storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-s3"
        S3_ENDPOINT: "http://localhost:4566"
        S3_BUCKET_NAME: "testing"
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"